name: Delete Action Cache Manually or on Branch Deletion
on:
  # branchが削除されたときにキャッシュを削除する
  pull_request_target:
    types: [closed]
  # 手動トリガー
  workflow_dispatch:

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/delete-action-cache@v1.0.1
