name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '27 0 * * *'
  push:
    # branches: [ "main" ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  #pull_request:
  #  branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: tetsuyainfra/openssh-server

jobs:
  # build-*ではランナーが走っているわけでないのでenv.*は共有されない
  # そのため、ここで再定義している
  setup:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ env.REGISTRY }}
    steps:
       - run: echo "All set!"

  build-amd64:
    needs: [setup]
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      registry: ${{ needs.setup.outputs.registry }}
      runs-on: ubuntu-latest
      target: amd64

  build-arm64:
    needs: [setup]
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      registry: ${{ needs.setup.outputs.registry }}
      runs-on: ubuntu-latest
      target: arm64

  create-manifest:
    permissions:
      contents: read
      # packages: write # needs to push to GitHub Container Registry
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Create & Push Manifest
        # Only push manifest on main branch not on PRs
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
        run: |
          DATE_TAG=$(date +'%Y%m%d')

          AMD64_DIGEST=${{ needs.build-amd64.outputs.digest }}
          ARM64_DIGEST=${{ needs.build-arm64.outputs.digest }}

          echo "manifest for $DATE_TAG"

          docker buildx imagetools create \
            -t $REGISTRY/$IMAGE_NAME:trixie-latest \
            -t $REGISTRY/$IMAGE_NAME:trixie-$DATE_TAG \
            $REGISTRY/$IMAGE_NAME@$AMD64_DIGEST \
            $REGISTRY/$IMAGE_NAME@$ARM64_DIGEST

      - name: Check Pushed Manifest
        # Only push manifest on main branch not on PRs
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
        run: |
          docker buildx imagetools inspect $REGISTRY/$IMAGE_NAME:trixie-latest
